# This configures the faceswap application frontend. The frontend serves
# public web traffic.
apiVersion: v1
kind: Service
metadata:
  name: faceswap
  labels:
    app: faceswap
    tier: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: http-server
  selector:
    app: faceswap
    tier: frontend
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: faceswap-frontend
  labels:
    app: faceswap
# The faceswap app replica set ensures that at least X
# instances of the faceswap app are running on the cluster.
# For more info about Pods see:
#   https://cloud.google.com/container-engine/docs/pods/
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: faceswap
        tier: frontend
    spec:
      containers:
      # Configuration for the app frontend container
      - name: faceswap-frontend
        image: gcr.io/cloud-next-php/faceswap-frontend
        # This setting makes nodes pull the docker image every time before
        # starting the pod. This is useful when debugging, but should be turned
        # off in production.
        imagePullPolicy: Always
        # The faceswap process listens on port 8080 for web traffic by default.
        ports:
        - name: http-server
          containerPort: 8080
        env:
        - name: PUBSUB_TOPIC
          valueFrom:
            configMapKeyRef:
              name: pubsub
              key: PUBSUB_TOPIC
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /etc/credentials/cloud-next-php.json
        - name: GCLOUD_PROJECT
          value: cloud-next-php
        volumeMounts:
            # name must match the volume name below
            - name: google-credentials
              mountPath: /etc/credentials
      volumes:
        - name: google-credentials
          secret:
            secretName: google-credentials


---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: faceswap-worker
  labels:
    app: faceswap
# The faceswap app replica set ensures that at least X
# instances of the faceswap worker are running on the cluster.
# For more info about Pods see:
#   https://cloud.google.com/container-engine/docs/pods/
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: faceswap
        tier: worker
    spec:
      containers:
      - name: faceswap-worker
        image: gcr.io/cloud-next-php/faceswap-worker
        # This setting makes nodes pull the docker image every time before
        # starting the pod. This is useful when debugging, but should be turned
        # off in production.
        imagePullPolicy: Always
        env:
        - name: PUBSUB_SUBSCRIPTION
          valueFrom:
            configMapKeyRef:
              name: pubsub
              key: PUBSUB_SUBSCRIPTION
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /etc/credentials/cloud-next-php.json
        - name: GCLOUD_PROJECT
          value: cloud-next-php
        volumeMounts:
            # name must match the volume name below
            - name: google-credentials
              mountPath: /etc/credentials
      volumes:
        - name: google-credentials
          secret:
            secretName: google-credentials
