# This configures the faceswap application frontend. The frontend serves
# public web traffic.
apiVersion: v1
kind: Service
metadata:
  name: faceswap-app
  labels:
    app: faceswap
    tier: app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: http-server
  selector:
    app: faceswap
    tier: app
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: faceswap-app
  labels:
    app: faceswap
# The faceswap app replica set ensures that at least 3
# instances of the faceswap app are running on the cluster.
# For more info about Pods see:
#   https://cloud.google.com/container-engine/docs/pods/
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: faceswap
        tier: app
    spec:
      containers:
      # Configuration for the app frontend container
      - name: faceswap-app
        # Pull from local repo
        image: faceswap-app
        # This setting makes nodes pull the docker image every time before
        # starting the pod. This is useful when debugging, but should be turned
        # off in production.
        imagePullPolicy: Never
        # The faceswap process listens on port 8080 for web traffic by default.
        ports:
        - name: http-server
          containerPort: 8080
---
# This configures the faceswap worker. The worker
# executes the faceswap logic
apiVersion: v1
kind: Service
metadata:
  name: faceswap-worker
  labels:
    app: faceswap
spec:
  ports:
    - port: 80
  selector:
    app: faceswap
    tier: worker
  clusterIP: None
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: faceswap-worker
  labels:
    app: faceswap
# The faceswap worker replica set ensures that at X instances of the
# faceswap worker pod are running on the cluster.
# For more info about Pods see:
#   https://cloud.google.com/container-engine/docs/pods/
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: faceswap
        tier: worker
    spec:
      containers:
      - name: faceswap-worker
        image: faceswap-worker
        # This setting makes nodes pull the docker image every time before
        # starting the pod. This is useful when debugging, but should be turned
        # off in production.
        imagePullPolicy: Never
        # The faceswap worker listens on port 8080 for web traffic by default.
        ports:
        - name: http-server
          containerPort: 8080
